baseURL = 'https://lex00.github.io/'
locale = 'en-us'
title = 'lex00'
theme = 'default'

[taxonomies]
  category = 'categories'
  tag = 'tags'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
